// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Satellite.Astronaut.Tracking.Data;

#nullable disable

namespace Satellite.Astronaut.Tracking.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250421164504_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Satellite.Astronaut.Tracking.Models.Astronaut", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Astronauts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ExperienceYears = 12,
                            FirstName = "Neil",
                            LastName = "Armstrong"
                        },
                        new
                        {
                            Id = 2L,
                            ExperienceYears = 8,
                            FirstName = "Sally",
                            LastName = "Ride"
                        },
                        new
                        {
                            Id = 3L,
                            ExperienceYears = 15,
                            FirstName = "Chris",
                            LastName = "Hadfield"
                        });
                });

            modelBuilder.Entity("Satellite.Astronaut.Tracking.Models.AstronautSatellite", b =>
                {
                    b.Property<long>("AstronautId")
                        .HasColumnType("bigint");

                    b.Property<long>("SatelliteId")
                        .HasColumnType("bigint");

                    b.HasKey("AstronautId", "SatelliteId");

                    b.HasIndex("SatelliteId");

                    b.ToTable("AstronautSatellites");

                    b.HasData(
                        new
                        {
                            AstronautId = 1L,
                            SatelliteId = 1L
                        },
                        new
                        {
                            AstronautId = 2L,
                            SatelliteId = 2L
                        },
                        new
                        {
                            AstronautId = 3L,
                            SatelliteId = 3L
                        });
                });

            modelBuilder.Entity("Satellite.Astronaut.Tracking.Models.Satellite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Decommissioned")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LaunchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OrbitType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Satellites");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Decommissioned = false,
                            LaunchDate = new DateTime(1990, 4, 24, 5, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hubble",
                            OrbitType = "LEO"
                        },
                        new
                        {
                            Id = 2L,
                            Decommissioned = false,
                            LaunchDate = new DateTime(2023, 8, 14, 5, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Starlink-17",
                            OrbitType = "MEO"
                        },
                        new
                        {
                            Id = 3L,
                            Decommissioned = false,
                            LaunchDate = new DateTime(2020, 11, 21, 6, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sentinel-6",
                            OrbitType = "LEO"
                        });
                });

            modelBuilder.Entity("Satellite.Astronaut.Tracking.Models.AstronautSatellite", b =>
                {
                    b.HasOne("Satellite.Astronaut.Tracking.Models.Astronaut", "Astronaut")
                        .WithMany("AstronautSatellites")
                        .HasForeignKey("AstronautId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Satellite.Astronaut.Tracking.Models.Satellite", "Satellite")
                        .WithMany("AstronautSatellites")
                        .HasForeignKey("SatelliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Astronaut");

                    b.Navigation("Satellite");
                });

            modelBuilder.Entity("Satellite.Astronaut.Tracking.Models.Astronaut", b =>
                {
                    b.Navigation("AstronautSatellites");
                });

            modelBuilder.Entity("Satellite.Astronaut.Tracking.Models.Satellite", b =>
                {
                    b.Navigation("AstronautSatellites");
                });
#pragma warning restore 612, 618
        }
    }
}
